### ISSUE TITLE
Environment Variables for db connection variables.

### ISSUE THREAD

**Issue by tmackenzie** [mybatis/migrations#10]
Given a user that wants to run migrations
When I specify that I want to use environment variables in my environment's setting file
```
envVariable.enabled=true
```

And I specify which environment variables to use for the connection settings:
```
envVariable.driver=DB_DRIVER
envVariable.url=DB_URL
envVariable.username=DB_USERNAME
envVariable.password=DB_PASSWORD
```

And I run `mvn migration:up` or `mvn migration:pending`
Then set up the db connection using the following: 
`DB_DRIVER` for the `driver` property,
`DB_URL` for the `url` property,
`DB_USERNAME` for the `username` property,
`DB_PASSWORD` for the `password` property
And successfully run the migrations.

I'm willing to code this feature If you would accept the PR.

**Comment by nmaves** [comment]
This feature already exists in the migrations application.  You can find out to set up different environments here [Init](http://mybatis.github.io/migrations/init.html).  Let me know if you are looking for something else and I am misunderstanding your request.

**Comment by dtanner** [comment]
If I'm understanding correctly, @tmackenzie is referring to system environment variables. e.g.   define and use something like `System.getenv("MYBATIS_DB_DRIVER")` instead of specifying a properties file.

**Comment by tmackenzie** [comment]
yes, I did refer to system environment variables. I have moved onto another migration maven plugin. best of luck.

**Comment by h3adache** [comment]
Is this still something people are requesting? There's no vote option for github so I can't tell lol

**Comment by dtanner** [comment]
FWIW - I don't need it, although it would be a nice to have feature.  Our current workaround is to use saltstack to dynamically configure the properties file per environment.  And for me the ideal solution would actually be for the migrations to pull their config from etcd, since that's what we're using as our centralized configuration management for our DB connection info.  I wouldn't expect that to be high on the feature list though.  By far the highest priority item for us is a separate test data migrations. i.e. Configurable migration groups.

**Comment by h3adache** [comment]
I've always used maven or gradle interpolation do what you just said without the use of saltstack. saltstack does look nice though lol For configurable migration groups, feel free to open an issue or post on the mailing list to discuss it there.

**Comment by hazendaz** [comment]
Based on comments here, it would appear there is a work around or otherwise it's already supported so I'm going to close the ticket.
