### ISSUE TITLE
Publish latest version to Maven Central?

### ISSUE THREAD

**Issue by jcohen** [mybatis/migrations#38]
The most recent version of mybatis-migrations on Maven Central is from 2014: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22mybatis-migrations%22 and is not compatible w/ MyBatis 3.3. Would it be possible to publish a more recent version of mybatis-migrations?

**Comment by hazendaz** [comment]
@jcohen I can push a release but I'm not quite sure that anything was done in regards to support of mybatis 3.3.x.  Looking over commits from now back to 2014, it's mostly build related.  Can you possible pull the latest snapshot of this and see if it's compatible.  If not, if you could kindly update compliance and submit a PR?

Snapshots are located here.

https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/mybatis-migrations/3.2.1-SNAPSHOT/

**Comment by jcohen** [comment]
Yeah, I've been using the snapshots for development, but I'm obviously wary of that for production code. I was also able to use the version from Maven Central by excluding its mybatis dependency in favor of our direct and up to date 3.3.1 dep, so I think it should be safe to just publish as is?

**Comment by emacarron** [comment]
@jcohen I am Ok with a refresh release but why is it not compatible with MB 3.3.1? I am also not aware of any change to make it work with 3.3.1 and build is passing.

**Comment by harawata** [comment]
> I was also able to use the version from Maven Central by excluding its mybatis dependency

There is nothing wrong with that approach :-)
Note that it does not mean that the current version of migrations is incompatible with core 3.3.1.

And I think you don't need to exclude because maven will use core 3.3.1 if you add it as a direct dependency of your project.
Alternatively, we can make the core dependency as 'provided', but then you will always have to add the core dependency by yourself.

**Comment by jcohen** [comment]
The exclusion just seemed like one extra step to jump through in order to get thinks working. It would be nice if migrations was published in coordination w/ core mybatis, but if that's not desirable from your perspective, I can continue using the exclude to ensure that my direct dependency takes precedence.

**Comment by hazendaz** [comment]
@jcohen You don't need the exclusion.  Maven will resolve the correct mybatis as long as you provide it in your POM.  I will however push a release after trying to clear out some issues and possibly get new functionality into migrations.  My main concern was the early comments that we magically did something that didn't exist in the wild which was not the case.  I'm perfectly fine with a release to show it's still maintained but wanted to be sure I wasn't missing something in what has occurred since last release.  I'll try to get this done in a week or so after giving some time to issues if any will be addressed.  Most are very old so we may see no changes other than the release.  I'll keep you posted...

**Comment by jcohen** [comment]
I'm using Gradle, so perhaps it behaves differently (though I [ended up using](https://github.com/apache/aurora/commit/5ecded788251bcaece0d972c963364f700aa9f3b#diff-c197962302397baf3a4cc36463dce5ea) Gradle's conflict resolution to force my desired MyBatis version rather than explicit exclude).

In any event, thanks for the diligent responses and appreciate the publish, even if there's no functional changes.

**Comment by hazendaz** [comment]
@jcohen Can you pull the latest snapshot and give it a try before we release this?  @harawata gave an assist along with various users rebasing to get some real fixes into the library.  That said, now we do have a valid reason to release and I wante to make sure this is still working as expected by someone using it (I don't use it!).

**Comment by harawata** [comment]
Released 3.2.1 😺
