### ISSUE TITLE
Errors During Bootstrap Process

### ISSUE THREAD

**Issue by RickFlist** [mybatis/migrations#49]
So I'm posting this here, I didn't see a forum or anything on StackOverflow for this...

I'm attempting to execute the bootstrap step. I've exported the schema from our production database using both Workbench and MySQLdump. I'm getting similar errors on both of them when executing MIGRATIS BOOTSTRAP:

**Error 1**
```
ERROR: Error running bootstrapper.  Cause: org.apache.ibatis.jdbc.RuntimeSqlException: Error executing: DELIMITER ;
.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manua
l that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER' at line 1
```

**Error 2**
```
ERROR: Error running bootstrapper.  Cause: org.apache.ibatis.jdbc.RuntimeSqlException: Error executing: /*!40101 SET @OLD_
SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */
.  Cause: java.sql.SQLWarning: Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future relea
se.
```

These errors persist regardless of the combination i use for `full_line_delimiter` or `auto_commit`

**Comment by h3adache** [comment]
Hi plz use mailing list for issues like this.
Post up your bootstrap.sql and your environment properties.

**Comment by harawata** [comment]
Hi @RickFlist ,

As a script generated by mysqldump may contain extended syntaxes for native clients, you may have to resolve each error manually.

1. To change the delimiter, you need to use the ```-- @DELIMITER``` syntax.

   ```
-- @DELIMITER ;
```
2. The warning is caused by the special comment in the dump file. Remove each problematic line or try adding [```--compact```](http://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_compact) to mysqldump command.

If you still have a problem, please follow @h3adache 's suggestion and ask it on the [mailing list](http://groups.google.com/group/mybatis-user).

Thank you!
Iwao

**Comment by RickFlist** [comment]
Thanks guys. I've posted to that group twice and my posts seem to disappear....
