### ISSUE TITLE
FEATURE: Use of multi-character delimiters

### ISSUE THREAD

**Issue by chb0github** [mybatis/migrations#96]
Discussed in #88

Currently the --@DELIMITER flag only accept a single character. Considering most programming languages are capable of using every character on the keyboard, frequently a multi-character delimiter is used.

**Comment by harawata** [comment]
Fixed in the core via https://github.com/mybatis/mybatis-3/commit/082bb34732ebdf532b34a57b7f8bbe11ffe7d9d6
That version of the core will be included in the next release (3.3.2).

It is also possible to verify the fix with the following steps.

- Replace older `mybatis-VERSION.jar` in $MIGRATIONS_HOME/lib` with the latest mybatis-3.4.6-SNAPSHOT.jar obtained from the [snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/mybatis/3.4.6-SNAPSHOT/).
- Edit the hardcoded JAR file name in the startup scripts in `$MIGRATIONS_HOME/bin/`.

Thank you!
